engines:
  rubocop:
    enabled: false
  golint:
    enabled: false
  eslint:
    enabled: true
  csslint:
    enabled: true
  radon:
    enabled: true
    config:
      python_version: 3
  pep8:
    enabled: true
  duplication:
    enabled: true
    config:
      languages:
      - python
      - javascript
ratings:
  paths:
  - "**.py"
